version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    env_file: ./.env
    volumes:
      - db_storage:/var/lib/postgresql/data
    restart: unless-stopped

  app-api:
    image: chauless/task-tracker-api
    ports:
      - "8080:8080"
    links:
      - postgres
      - rabbitmq
    env_file: ./.env
    restart: on-failure
    
  app-email-sender:
    image: chauless/task-tracker-email-sender
    links:
      - rabbitmq
    env_file: ./.env
    restart: unless-stopped

  app-scheduler:
    image: chauless/task-tracker-scheduler
    links:
      - postgres
      - rabbitmq
    env_file: ./.env
    restart: unless-stopped
  
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_storage:/data
    
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ./.env
    volumes:
      - './rabbitmq:/var/lib/rabbitmq'

volumes:
  db_storage:
  redis_storage: